### ISSUE TITLE
Add support for property paths

### ISSUE THREAD

**Issue by gkellogg** [ruby-rdf/sparql#13]

**Comment by lks128** [comment]
Hello, I'm having a bad luck parsing a query with path expression. The query works just fine in Protege 5.1.0.

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?class (group_concat(DISTINCT ?item;separator=",") as ?keys) WHERE {
  ?class rdf:type owl:Class .
  ?class owl:hasKey ?key .
  ?key rdf:rest*/rdf:first ?item .
}
GROUP BY ?class ?key
```

STDERR output: https://gist.github.com/b36694c3a1577944acbecad4262deef9
bundle output: https://gist.github.com/anonymous/d83b285d1e77b830f0b0436ef19d400e
Ruby version: ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux]
