### ISSUE TITLE
Add a fully featured SPARQL 1.1 Protocol server w/ binary

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/sparql#22]
Where something like `sparql-server -p 8080 myfile.ttl` and `sparql-server -p 8081 http://example.org/myfile.ttl` work to start a SPARQL server with named graph support, POST/direct-POST queries, etc...

**Comment by bendiken** [comment]
:+1:

**Comment by gkellogg** [comment]
This could be added as a --server option to bin/sparql easily enough; There is a test application in spec/sinatra_spec.rb, which could easily serve as the basis of this.

**Comment by bendiken** [comment]
@gkellogg That would work, although conceptually it might be somewhat clearer if the `sparql` binary were to operate in a subcommand manner, such as:

* `sparql parse query.rq`
* `sparql execute query.rq data.ttl`
* `sparql server http://localhost:8080/sparql data.ttl`
* `sparql query http://localhost:8080/sparql query.rq`

This would make it an indispensable Swiss army knife of sorts for all SPARQL users. What do you think?

**Comment by gkellogg** [comment]
That would be fine. I'm a bit tied up for now, so feel free to tackle this if you have the time.

**Comment by gkellogg** [comment]
@bendiken: I got a start on it. The Rack/Sinatra stuff is commented out, as I need to figure more about provisioning from a ruby file. I also added (but didn't test) querying a remote endoint with sparql-client.

**Comment by bendiken** [comment]
@gkellogg Looks good, will give you some feedback tomorrow once I sort out my currently-broken Ruby install...
