### ISSUE TITLE
Update query keywords are case-sensitive

### ISSUE THREAD

**Issue by ijdickinson** [ruby-rdf/sparql#24]
According to https://www.w3.org/TR/sparql11-query/#sparqlGrammar (note 1), SPARQL keywords are treated as case insensitive. This appears to be true for RDF Ruby's SPARQL queries, but not for SPARQL updates.

Test case:

    require "minitest/autorun"
    require "sparql"

    class CaseInsensitiviyInKeywordsTest < Minitest::Test
      NS = "http://foo.bar/".freeze

      def test_select_with_lower_case
        parsed = SPARQL.parse("select * {?s ?p ?o}", update: false)
        refute_nil parsed
      end

      def test_select_with_upper_case
        parsed = SPARQL.parse("SELECT * {?s ?p ?o}", update: false)
        refute_nil parsed
      end

      def test_update_with_lower_case
        parsed = SPARQL.parse("insert data {<#{NS}a> <#{NS}b> <#{NS}b>}", update: true)
        refute_nil parsed
      end

      def test_update_with_upper_case
        parsed = SPARQL.parse("INSERT DATA {<#{NS}a> <#{NS}b> <#{NS}b>}", update: true)
        refute_nil parsed
      end
    end

Expected: four tests pass. Currently with `RDF::Sparql` 2.0, `test_update_with_lower_case` throws a parse exception:

    Error:
    CaseInsensitiviyInKeywordsTest#test_update_with_lower_case:
    EBNF::LL1::Parser::Error: ERROR [line: 1] Expected one of [:_eps, "BASE", "PREFIX", "LOAD", 
    "CLEAR", "DROP", "ADD", "MOVE", "COPY", "CREATE", "INSERT DATA", "DELETE DATA", "DELETE
      WHERE", "WITH", "INSERT", "DELETE"] (found "insert data"), production = :UpdateUnit
      test/models/case_insensitivity_in_keywords_test.rb:18:in `test_update_with_lower_case'

**Comment by gkellogg** [comment]
@ijdickinson let me know if this addresses your issues, and I'll release an updated gem. (Not sure why the code that was causing the problem was introduced in the first place!).

**Comment by ijdickinson** [comment]
@gkellogg I can confirm that this fixes the presenting issue in my code. Thanks Gregg!
