### ISSUE TITLE
Link to SPARQL S-Expressions (SSE) is down

### ISSUE THREAD

**Issue by o314** [ruby-rdf/sparql#34]
In the readme file, section Description;, it is mentionned that 

>* {SPARQL::Grammar} implements a [SPARQL 1.1 Query][] and [SPARQL 1.1 Update][] parser generating [SPARQL S-Expressions (SSE)][SSE].

The openjena project seems to have disappeared from the net.

Can we use [SSE2] at Apache as a primary reference ?

[SSE]:              http://openjena.org/wiki/SSE
[SSE2]:              https://jena.apache.org/documentation/notes/sse.html

**Comment by gkellogg** [comment]
Thanks for pointing this out.

**Comment by o314** [comment]
Thanks you for your reactivity.
