### ISSUE TITLE
Wrong permissions in gem files

### ISSUE THREAD

**Issue by Richard-Degenne** [ruby-rdf/sparql#44]
Hello,

The latest versions of the gem (3.2.1 and 3.2.2 at least, from my testing) suffer from weird file permission issues on some operator files.

# Steps to reproduce

1. Create a folder `sparql-bug` and move inside it.

```bash
mkdir sparql-bug && cd $_
```

2. Create a minimalistic Dockerfile as such. (Running from a Docker container makes it easy to run with different UID, which triggers the bug.)

```dockerfile
FROM ruby:2.6-alpine

RUN apk add --no-cache build-base && \
    gem install sparql -v '= 3.2.2'

ENTRYPOINT ["/usr/local/bundle/bin/sparql"]
```

3. Build the image

```bash
docker build . -t sparql-bug:xxx
```

4. Create a sample SPARQL query file

```bash
echo "SELECT * WHERE { ?s ?p ?o }" > query.sparql
```

5. Run the Docker image and see that the command works.

```bash
docker run --rm -ti -v $PWD:/data:ro sparql-bug:xxx parse /data/query.sparql
```

6. Run the same command with a `-u` flag to run as a different user.

```
docker run --rm -ti -u $(id -u) -v $PWD:/data:ro sparql-bug:xxx parse /data/query.sparql
```

## Expected behavior

The command outputs the same result as the previous one.

## Observed behaivor

The command fails with the following error.

```text
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- sparql/algebra/operator/triple (LoadError)
        from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
        from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
        from /usr/local/bundle/gems/sparql-3.2.2/lib/sparql/algebra/expression.rb:146:in `new'
        from /usr/local/bundle/gems/sparql-3.2.2/lib/sparql/algebra/expression.rb:86:in `for'
        from /usr/local/bundle/gems/sparql-3.2.2/lib/sparql/grammar/parser11.rb:827:in `block in <class:Parser>'
        from /usr/local/bundle/gems/ebnf-2.3.1/lib/ebnf/ll1/parser.rb:640:in `block in onFinish'
        from /usr/local/bundle/gems/ebnf-2.3.1/lib/ebnf/ll1/parser.rb:158:in `block in eval_with_binding'
        from /usr/local/bundle/gems/ebnf-2.3.1/lib/ebnf/ll1/parser.rb:158:in `instance_eval'
        from /usr/local/bundle/gems/ebnf-2.3.1/lib/ebnf/ll1/parser.rb:158:in `eval_with_binding'
        from /usr/local/bundle/gems/ebnf-2.3.1/lib/ebnf/ll1/parser.rb:639:in `onFinish'
        from /usr/local/bundle/gems/ebnf-2.3.1/lib/ebnf/ll1/parser.rb:442:in `parse'
        from /usr/local/bundle/gems/sparql-3.2.2/lib/sparql/grammar/parser11.rb:2115:in `parse'
        from /usr/local/bundle/gems/sparql-3.2.2/lib/sparql/grammar.rb:255:in `parse'
        from /usr/local/bundle/gems/sparql-3.2.2/bin/sparql:45:in `run'
        from /usr/local/bundle/gems/sparql-3.2.2/bin/sparql:136:in `<top (required)>'
        from /usr/local/bundle/bin/sparql:23:in `load'
        from /usr/local/bundle/bin/sparql:23:in `<main>'
```
# Additional notes

The `require` of `sparql/algebra/operator/triple` fails because, in the second command, we are a different user than `root`.

Use the following command to look up the permissions of these files.

```bash
docker run --rm -ti --entrypoint /bin/sh sparql-bug:xxx -c 'ls -l /usr/local/bundle/gems/sparql-3.2.*/lib/sparql/algebra/operator'
```

```
total 608
-rw-r--r--    1 root     root          1460 May  5 08:59 abs.rb
-rw-r--r--    1 root     root          2597 May  5 08:59 add.rb
[...]
-rw-r--r--    1 root     root          1761 May  5 08:59 timezone.rb
-rw-------    1 root     root          1673 May  5 08:59 triple.rb
-rw-r--r--    1 root     root          1512 May  5 08:59 tz.rb
[...]
```

We can see that almost every file here has a 644 permission value (`-rw-r--r--`), except for `triple.rb` that has 600 permissions (`-rw-------`). These permissions mean that the file is not readable for any user other than root, which, in turn, prevents Ruby from loading the file.

## Workaround

It is possible to circumvent this issue by manually fixing the permissions in the Dockerfile with `chmod`.

```dockerfile
FROM ruby:2.6-alpine

RUN apk add --no-cache build-base && \
    gem install sparql -v '= 3.2.2'

# This fixes the missing permissions
RUN chmod -R a+r /usr/local/bundle/gems/sparql-*/lib

ENTRYPOINT ["/usr/local/bundle/bin/sparql"]
```

## Build and release workflow?

The most interesting part in this bug is that everything is okay on the GitHub repository itself, but the problem gets triggered when downloading the gem from rubygems.org.

@gkellogg: I see that the GitHub actions of this repository do not mention anything about building and releasing the gem. Do you perform these operations manually from your workstation? If that is the case, maybe the erroneous permissions come from your local setup, like a unusual `umask` value, for instance?

**Comment by gkellogg** [comment]
Extracting files from the gem shows just two files with mode 600: table.rb and triple.rb. In the directory used to generate the gem, the permissions are correct, and this doesn't affect any other gems, to the best I can see. It's somewhat mysterious as to how these were set, but a search shows some similar issues related to bundler: https://github.com/rubygems/bundler/issues/2136 (but from way back when).

I have a few other things to get into an updated release, which I'll get to later today, and yank 3.2.2. Note, when extracting 3.2.1, I didn't find any file permission problems.

**Comment by gkellogg** [comment]
I've released 3.2.3 and yanked 3.2.2. No explanation for why file permissions were bad, but I verified them in the new gem version before publishing.

**Comment by jperville** [comment]
Hello @gkellogg this is interesting (I helped @Richard-Degenne troubleshoot that issue).

No idea at all how the wrong permissions ended up in the built gem.

**Comment by jperville** [comment]
Hello @gkellogg  can you push the code of the new release on github too ?

On https://github.com/ruby-rdf/sparql/releases the last release is still 3.2.2 while on https://rubygems.org/gems/sparql is is 3.2.3

**Comment by gkellogg** [comment]
The code is up, I still need to publish the release note, which I’ll do later today.
